version: 0.1.{build}
build:
  verbosity: minimal
platform:
- Any CPU
configuration:
- Release
artifacts:
- path: PhotoCull\bin\$(configuration)\PhotoCull.exe
deploy:
- provider: GitHub
  auth_token:
    secure: oy9vmWoKGVoCQo1SmAaMu/j8ZEBCMCr7jbkPQ0CdJVwaY0MNwYqi/yqHlH6DIoFG
  artifact: /PhotoCull\\bin\\.*\\PhotoCull\.exe/
  on:
    appveyor_repo_tag: true
