version: 0.1.{build}
build:
  verbosity: minimal
platform:
- Any CPU
configuration:
- Release
artifacts:
- path: PhotoCull\bin\$(configuration)\PhotoCull.exe
  name: Executable
deploy:
- provider: GitHub
  auth_token:
    secure: oy9vmWoKGVoCQo1SmAaMu/j8ZEBCMCr7jbkPQ0CdJVwaY0MNwYqi/yqHlH6DIoFG
  artifact: Executable
  on:
    appveyor_repo_tag: true
